// <auto-generated />
using System;
using ConsoleUI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleUI.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20210912090631_dbSetUp")]
    partial class dbSetUp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.6.21352.1");

            modelBuilder.Entity("ConsoleUI.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Credit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Debit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Default")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Transfer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Account");
                });

            modelBuilder.Entity("ConsoleUI.MasterKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("NextKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextTerm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MasterKeys");
                });

            modelBuilder.Entity("ConsoleUI.Transact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payee")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transacts");
                });

            modelBuilder.Entity("ConsoleUI.TransactDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TransactId");

                    b.ToTable("TransactDetails");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TransactDetail");
                });

            modelBuilder.Entity("ConsoleUI.CreditAccount", b =>
                {
                    b.HasBaseType("ConsoleUI.Account");

                    b.Property<decimal>("Limit")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("CreditAccount");
                });

            modelBuilder.Entity("ConsoleUI.GeneralAccount", b =>
                {
                    b.HasBaseType("ConsoleUI.Account");

                    b.HasDiscriminator().HasValue("GeneralAccount");
                });

            modelBuilder.Entity("ConsoleUI.TradingAccount", b =>
                {
                    b.HasBaseType("ConsoleUI.Account");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("TradingAccount");
                });

            modelBuilder.Entity("ConsoleUI.ForexTransactDetail", b =>
                {
                    b.HasBaseType("ConsoleUI.TransactDetail");

                    b.Property<decimal>("ForexAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForexCurrency")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ForexTransactDetail");
                });

            modelBuilder.Entity("ConsoleUI.GeneralTransactDetail", b =>
                {
                    b.HasBaseType("ConsoleUI.TransactDetail");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("GeneralTransactDetail");
                });

            modelBuilder.Entity("ConsoleUI.TradingTransactDetail", b =>
                {
                    b.HasBaseType("ConsoleUI.TransactDetail");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Unit")
                        .HasColumnType("TEXT");

                    b.HasIndex("TradingAccountId");

                    b.HasDiscriminator().HasValue("TradingTransactDetail");
                });

            modelBuilder.Entity("ConsoleUI.TransferTransactDetail", b =>
                {
                    b.HasBaseType("ConsoleUI.TransactDetail");

                    b.Property<string>("LinkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkOrder")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferId")
                        .HasColumnType("TEXT");

                    b.HasIndex("TransferId");

                    b.HasDiscriminator().HasValue("TransferTransactDetail");
                });

            modelBuilder.Entity("ConsoleUI.CreditTransactDetail", b =>
                {
                    b.HasBaseType("ConsoleUI.GeneralTransactDetail");

                    b.HasDiscriminator().HasValue("CreditTransactDetail");
                });

            modelBuilder.Entity("ConsoleUI.Transact", b =>
                {
                    b.HasOne("ConsoleUI.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ConsoleUI.TransactDetail", b =>
                {
                    b.HasOne("ConsoleUI.Transact", null)
                        .WithMany("TransactDetail")
                        .HasForeignKey("TransactId");
                });

            modelBuilder.Entity("ConsoleUI.TradingTransactDetail", b =>
                {
                    b.HasOne("ConsoleUI.TradingAccount", "TradingAccount")
                        .WithMany()
                        .HasForeignKey("TradingAccountId");

                    b.Navigation("TradingAccount");
                });

            modelBuilder.Entity("ConsoleUI.TransferTransactDetail", b =>
                {
                    b.HasOne("ConsoleUI.Account", "Transfer")
                        .WithMany()
                        .HasForeignKey("TransferId");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("ConsoleUI.Transact", b =>
                {
                    b.Navigation("TransactDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
